# Generated by Django 3.1.4 on 2021-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursePic',
            field=models.ImageField(blank=True, default='t.png', upload_to='course_pics/'),
        ),
    ]
