# Generated by Django 3.1.3 on 2020-12-03 06:55

import courseManagementSystem.enrolledFields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagementSystem', '0002_auto_20201202_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['enroll']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['enroll']},
        ),
        migrations.AddField(
            model_name='content',
            name='enroll',
            field=courseManagementSystem.enrolledFields.EnrollField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='enroll',
            field=courseManagementSystem.enrolledFields.EnrollField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
