# Generated by Django 3.1.4 on 2021-01-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagementSystem', '0005_auto_20210107_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='t.png', upload_to='course_pics/'),
        ),
    ]
