# Generated by Django 3.1.4 on 2021-01-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagementSystem', '0006_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
