# Generated by Django 3.1.3 on 2020-11-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('userType', models.CharField(max_length=150)),
                ('profilePic', models.ImageField(blank=True, upload_to='profile_pics')),
            ],
        ),
    ]
