# Generated by Django 3.1.3 on 2020-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profilePic',
            field=models.ImageField(blank=True, default='profile.png', upload_to='profile_pics/'),
        ),
    ]
